title: James Ingold
description: "Javascript, Kubernetes, NodeJS Blog | I build things | Developer | Entreprenuer"
author:
  name: "James Ingold"
  email: "yo@jamesiingold.com"
  url: "https://jamesingold.com"
twitter:
  username: jamesingold
  card: summary
social:
  name: James Ingold
  links:
    - https://twitter.com/james_ingold    
    - https://www.linkedin.com/in/james-ingold-44153183/    
    - https://github.com/james-ingold

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "James Ingold"
year : "2020"
